import os


DEEPSEEK_BASE_URL = "https://api.deepseek.com"
DEEPSEEK_MODEL = os.getenv("DEEPSEEK_MODEL", "deepseek-v4-flash")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")

SIMULATION_DT_SECONDS = 1.0
HISTORIAN_DB = "distillation_history.sqlite"

FEED_TANK_MAX_CAPACITY_L = 1000.0
DISTILLATE_TANK_MAX_CAPACITY_L = 500.0
BOTTOMS_TANK_MAX_CAPACITY_L = 500.0
FEED_SUPPLY_FLOW_LPM = 10.0
PRODUCT_EXPORT_FLOW_LPM = 20.0
PRODUCT_EXPORT_START_LEVEL = 60.0
PRODUCT_EXPORT_STOP_LEVEL = 10.0
TANK_CAPACITY_TRIP_LEVEL = 90.0

PRESSURE_HIGH = 125.0
PRESSURE_HIGH_HIGH = 140.0
FEED_TANK_LOW_LOW = 10.0
FEED_TANK_HIGH_HIGH = 80.0
BOTTOM_LOW_LOW = 15.0
REFLUX_DRUM_HIGH_HIGH = 85.0

TOP_TEMP_SETPOINT = 79.0
BOTTOM_TEMP_SETPOINT = 100.0
PRESSURE_SETPOINT = 105.0
REFLUX_DRUM_LEVEL_SETPOINT = 50.0
BOTTOM_LEVEL_SETPOINT = 55.0
